---
title: "Mapas Eleitorais com R"
author: "Lucas Gelape, João V. Guedes-Neto e Marco Antonio Faganello"
#date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
url: https://gv-cepesp.github.io/mapaseleitorais2023/
#description: |
#  Texto
#link-citations: yes
#github-repo: https://github.com/GV-CEPESP/mapaseleitorais2023
---

# Sobre o Workshop

Em 2018, PT e PSL protagonizaram a disputa pela presidência. Como mostrou uma [reportagem do site Pindograma](https://pindograma.com.br/2020/09/18/polarizacoes.html), no Capão Redondo, a disputa para deputado reproduziu essa tendência. Porém, em Pinheiros, os mais votados saíram desse padrão: foram PSOL e Novo. Mapas eleitorais permitem investigar esse fenômeno.

O objetivo desse workshop é ensinar os participantes a trabalhar com dados espaciais no R a partir de informações eleitorais. Nele, vamos apresentar algumas características e cuidados especiais com esse tipo de dados, como associar os resultados eleitorais ao espaço (inclusive intramunicipais), e a produzir mapas.

## Informações básicas

* **Dia**: 19 de novembro de 2023
* **Horário**: 11h15

Esse workshop é parte da programação do [Coda.Br 2023](https://escoladedados.org/coda/coda2023/).

Todas as bases de dados necessárias para as atividades estão disponíveis [neste link](https://github.com/GV-CEPESP/mapaseleitorais2023/tree/main/base).

## Pré-Requisitos

R, RStudio, pacotes (`tidyverse` e `sf`).

## Autores

[Lucas Gelape](https://lgelape.github.io/) é pesquisador de pós-doutorado no FGV CEPESP, doutor em Ciência Política pela Universidade de São Paulo. Atualmente, pesquisa temas relacionados a política local e geografia eleitoral. No jornalismo, trabalhou no G1 e no Volt Data Lab/Núcleo.

[João V. Guedes-Neto](https://joaoguedesneto.github.io/) é pesquisador de pós-doutorado no FGV CEPESP, doutor em Ciência Política pela Universidade de Pittsburgh. É especialista em psicologia política, investigando o comportamento dos eleitores, políticos e burocratas. Antes de retornar ao Brasil, foi professor na Kean University (Nova Jersey, EUA).

[Marco Antonio Faganello](https://github.com/marcofaga) é pesquisador, cientista de dados e pós-doutorando no FGV CEPESP, doutor em Ciência Política pela Universidade Estadual de Campinas (UNICAMP). Atualmente, pesquisa temas relacionados à eleições, partidos, direita e geografia eleitoral.

## Como citar

Gelape, Lucas; Guedes-Neto, João Victor; Faganello, Marco Antonio. **Mapas Eleitorais com R**. São Paulo, 2023. Disponível em: https://gv-cepesp.github.io/mapaseleitorais2023/
